# Enumere las tareas de inicio. Obtenga m치s informaci칩n https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: yarn
    init: yarn install
    command: yarn dev

# Enumere los puertos a exponer. Obtenga m치s informaci칩n https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: false
    addBadge: true
